In [1]:
#Load libraries
import numpy as np 
import pandas as pd 
import warnings
warnings.filterwarnings('ignore')
import matplotlib.pyplot as plt
import seaborn as sns
import os

In [2]:
#Load dataset about melanoma
dataset_melanoma = pd.read_csv('/Users/ESTHER/Desktop/CathedralSW/melanoma.csv')

In [3]:
#features of the datset
dataset_melanoma.shape
dataset_melanoma.columns
dataset_melanoma

pos  time  status  sex  age  year  thickness  ulcer
0      1    10       3    1   76  1972       6.76      1
1      2    30       3    1   56  1968       0.65      0
2      3    35       2    1   41  1977       1.34      0
3      4    99       3    0   71  1968       2.90      0
4      5   185       1    1   52  1965      12.08      1
5      6   204       1    1   28  1971       4.84      1
6      7   210       1    1   77  1972       5.16      1
7      8   232       3    0   60  1974       3.22      1
8      9   232       1    1   49  1968      12.88      1
9     10   279       1    0   68  1971       7.41      1
10    11   295       1    0   53  1969       4.19      1
11    12   355       3    0   64  1972       0.16      1
12    13   386       1    0   68  1965       3.87      1
13    14   426       1    1   63  1970       4.84      1
14    15   469       1    0   14  1969       2.42      1
15    16   493       3    1   72  1971      12.56      1
16    17   529       1    1   46  1971       5.80      1
17    18   621       1    1   72  1972       7.06      1
18    19   629       1    1   95  1968       5.48      1
19    20   659       1    1   54  1972       7.73      1
20    21   667       1    0   89  1968      13.85      1
21    22   718       1    1   25  1967       2.34      1
22    23   752       1    1   37  1973       4.19      1
23    24   779       1    1   43  1967       4.04      1
24    25   793       1    1   68  1970       4.84      1
25    26   817       1    0   67  1966       0.32      0
26    27   826       3    0   86  1965       8.54      1
27    28   833       1    0   56  1971       2.58      1
28    29   858       1    0   16  1967       3.56      0
29    30   869       1    0   42  1965       3.54      0
..   ...   ...     ...  ...  ...   ...        ...    ...
175  176  3402       2    1   50  1968       1.62      0
176  177  3441       2    0   20  1968       0.65      0
177  178  3458       3    0   54  1967       1.45      0
178  179  3459       2    0   29  1968       0.65      0
179  180  3459       2    1   56  1968       1.29      1
180  181  3476       2    0   60  1968       1.62      0
181  182  3523       2    0   46  1968       3.54      0
182  183  3667       2    0   42  1967       3.22      0
183  184  3695       2    0   34  1967       0.65      0
184  185  3695       2    0   56  1967       1.03      0
185  186  3776       2    1   12  1967       7.09      1
186  187  3776       2    0   21  1967       1.29      1
187  188  3830       2    1   46  1967       0.65      0
188  189  3856       2    0   49  1967       1.78      0
189  190  3872       2    0   35  1967      12.24      1
190  191  3909       2    1   42  1967       8.06      1
191  192  3968       2    0   47  1967       0.81      0
192  193  4001       2    0   69  1967       2.10      0
193  194  4103       2    0   52  1966       3.87      0
194  195  4119       2    1   52  1966       0.65      0
195  196  4124       2    0   30  1966       1.94      1
196  197  4207       2    1   22  1966       0.65      0
197  198  4310       2    1   55  1966       2.10      0
198  199  4390       2    0   26  1965       1.94      1
199  200  4479       2    0   19  1965       1.13      1
200  201  4492       2    1   29  1965       7.06      1
201  202  4668       2    0   40  1965       6.12      0
202  203  4688       2    0   42  1965       0.48      0
203  204  4926       2    0   50  1964       2.26      0
204  205  5565       2    0   41  1962       2.90      0

[205 rows x 8 columns]

In [4]:
# For the  regression  choose the columns "years" and "thickness"
x = dataset_melanoma.iloc[:,[4,6]].values
x

array([[76.  ,  6.76],
       [56.  ,  0.65],
       [41.  ,  1.34],
       [71.  ,  2.9 ],
       [52.  , 12.08],
       [28.  ,  4.84],
       [77.  ,  5.16],
       [60.  ,  3.22],
       [49.  , 12.88],
       [68.  ,  7.41],
       [53.  ,  4.19],
       [64.  ,  0.16],
       [68.  ,  3.87],
       [63.  ,  4.84],
       [14.  ,  2.42],
       [72.  , 12.56],
       [46.  ,  5.8 ],
       [72.  ,  7.06],
       [95.  ,  5.48],
       [54.  ,  7.73],
       [89.  , 13.85],
       [25.  ,  2.34],
       [37.  ,  4.19],
       [43.  ,  4.04],
       [68.  ,  4.84],
       [67.  ,  0.32],
       [86.  ,  8.54],
       [56.  ,  2.58],
       [16.  ,  3.56],
       [42.  ,  3.54],
       [65.  ,  0.97],
       [52.  ,  4.83],
       [58.  ,  1.62],
       [60.  ,  6.44],
       [68.  , 14.66],
       [75.  ,  2.58],
       [19.  ,  3.87],
       [66.  ,  3.54],
       [56.  ,  1.34],
       [46.  ,  2.24],
       [58.  ,  3.87],
       [74.  ,  3.54],
       [65.  , 17.42],
       [64.

In [5]:
#target column
y= dataset_melanoma.iloc[:,7].values
y

array([1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 0], dtype=int64)

In [6]:
# Split the dataset into Training and Testing set
from sklearn.cross_validation import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25,random_state=0)

C:\Users\ESTHER\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [7]:
#Standardize features by removing the mean and scaling to unit variance
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [8]:
#Show X_train
x_train

array([[-0.99131798, -0.73200168],
       [ 0.97286366, -0.47912591],
       [-0.31613054, -0.05997564],
       [-0.00922716,  0.38688704],
       [ 0.29767622, -0.6731128 ],
       [-1.60512474, -0.28167495],
       [-0.50027257, -0.50683832],
       [ 0.97286366,  0.72290006],
       [ 0.78872163, -0.61768798],
       [-0.31613054, -0.73200168],
       [ 0.3590569 ,  0.38688704],
       [-0.56165324, -0.39252461],
       [-0.43889189, -0.84285134],
       [ 1.95495447,  0.46309618],
       [ 0.78872163, -0.39252461],
       [ 0.11353419,  1.72401102],
       [ 0.72734095, -0.72853763],
       [-0.37751122,  1.72401102],
       [-1.60512474, -0.50683832],
       [ 0.23629554, -0.59690367],
       [ 1.46390906, -0.50683832],
       [-0.43889189, -0.50683832],
       [-0.25474986, -0.6731128 ],
       [ 0.17491487, -0.05997564],
       [-1.05269865, -0.6731128 ],
       [ 0.3590569 , -0.84285134],
       [-1.72788609, -0.45141349],
       [ 1.15700568, -0.1708253 ],
       [-1.42098271,

In [9]:
#Fit the logistic regression 
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=0, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [10]:
#Predic the Test set results
y_pred = classifier.predict(x_test)
y_pred

array([0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 0], dtype=int64)

In [11]:
# Compute confusion matrix to evaluate the accuracy of a classification
from sklearn.metrics import confusion_matrix
conf_matrix = confusion_matrix(y_test,y_pred)
conf_matrix

array([[24,  4],
       [12, 12]], dtype=int64)

In [13]:
from sklearn import metrics
print (metrics.accuracy_score(y_test,classifier.predict(x_test)))

0.6923076923076923


In [18]:
from sklearn import linear_model
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
# Create linear regression object
regr = linear_model.LinearRegression()

# Train the model using the training sets
regr.fit(x_train, y_train)

# Make predictions using the testing set
y_pred = regr.predict(x_test)

# The coefficients
print('Coefficients: \n', regr.coef_)
# The mean squared error
print("Mean squared error: %.2f"
      % mean_squared_error(y_test, y_pred))
# Explained variance score: 1 is perfect prediction
print('Variance score: %.2f' % r2_score(y_test, y_pred))


Coefficients: 
 [0.01108431 0.2099865 ]
Mean squared error: 0.21
Variance score: 0.17
